### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by rrsuyama** [xvtyzn/nyankomicro#6]
こんにちは、大阪大学生命機能研究科の須山と申します。現在16Sアンプリコン解析で こちらのnyankomicroのコードを使用しているのですが、データソースが異なるためだと思うのですが、うまく機能しない箇所があり、お伺い致したく思います。この場所で良いでしょうか。よろしくお願いいたします。

**Comment by xvtyzn** [comment]
須山様

こんにちは。
こちらでエラー等伺ってもよろしいでしょうか。Rでのエラーメッセージとinputにしたデータセットについて詳細伺えればと思います。もし、データの制約や公開が難しいとのことでしたら、以下のメールまでご連絡いただければ幸いです。

ide_0109☆outlook.jp
※☆を@に変更してください。

よろしくお願いします。

井手
